[config]
seq_len = 720
pred_len = 96
seg_size = 8
dropout = 0.05
num_map = 2
kernel_size = 8
conv_stride = 4
c = 7
topk = -1
epochs = 200
lr = 5e-5
batch_size = 64
step_size = 20
gamma = 0.75
period = 24
use_pi = true