[config]
seq_len = 336
pred_len = 96
seg_size = 4
dropout = 0.05
num_map = 4
kernel_size = 8
conv_stride = 4
c = 7
topk = -1
epochs = 200
lr = 5e-5
batch_size = 64
step_size = 20
gamma = 0.75
period = 96
use_pi = true