[config]
seq_len = 720
pred_len = 96
seg_size = 4
dropout = 0.05
num_map = 8
kernel_size = 8
conv_stride = 4
c = 862
topk = -1
epochs = 200
lr = 0.0008
batch_size = 64
step_size = 20
gamma = 0.75
period = 168
use_pi = true